# SOURCE: https://install.portworx.com/?operator=true&mc=false&kbver=1.22.4&b=true&s=%2Fdev%2Fsdc&j=auto&kd=%2Fdev%2Fsdb&m=eth1&d=eth1&c=px-asustuf-cluster-7208c62c-0c76-4157-b2eb-b6391a19e9fe&stork=true&csi=true&mon=true&tel=false&st=k8s&promop=true
kind: StorageCluster
apiVersion: core.libopenstorage.org/v1
metadata:
  name: px-vboxlab-cluster
  namespace: kube-system
  annotations:
    portworx.io/install-source: "https://install.portworx.com/?operator=true&mc=false&kbver=1.22.4&b=true&s=%2Fdev%2Fsdc&j=auto&kd=%2Fdev%2Fsdb&m=eth1&d=eth1&c=px-asustuf-cluster-7208c62c-0c76-4157-b2eb-b6391a19e9fe&stork=true&csi=true&mon=true&tel=false&st=k8s&promop=true"
spec:
  image: portworx/oci-monitor:2.9.1.1
  imagePullPolicy: IfNotPresent
  kvdb:
    internal: true
  storage:
    devices:
    - /dev/sdd
    journalDevice: auto
    kvdbDevice: /dev/sdc
  network:
    dataInterface: enp0s8
    mgmtInterface: enp0s8
  secretsProvider: k8s
  stork:
    image: openstorage/stork:2.8.2
    enabled: true
    args:
      webhook-controller: "true"
  autopilot:
    enabled: true
  monitoring:
    prometheus:
      enabled: true
      exportMetrics: true
  featureGates:
    CSI: "true"
  nodes:
  - selector:
      #nodeName: <node-1>
      labelSelector:
        matchLabels:
          portworx.io/node-type: storageless
    storage:
      devices:
    network:
      dataInterface: enp0s8
      mgmtInterface: enp0s8
